# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_SecretsManager.3
 
  ## What does this document do?
  This document deletes a secret that has been unused for the number of days specified in the unusedForDays parameter (Default: 90 days).
  There is a 30 day period to recover the secret after it is deleted.
  [DeleteSecret](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html) API.
 
  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * RemediationRoleName: (Optional) The name of the role that allows Automation to remediate the finding on your behalf.
 
  ## Output Parameters
  * Remediation.Output
 
  ## Documentation Links
  * [AWS FSBP v1.0.0 SecretsManager.3](https://docs.aws.amazon.com/securityhub/latest/userguide/secretsmanager-controls.html#secretsmanager-3)
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the SecretsManager.3 finding
  RemediationRoleName:
    type: 'String'
    default: 'SO0111-RemoveUnusedSecret'
    allowedPattern: '^[\w+=,.@-]+$'

outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
 
mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding.Id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.finding.ProductArn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: SecretARN
        Selector: $.Payload.resource_id
        Type: String
      - Name: RemediationRegion
        Selector: $.Payload.resource_region
        Type: String
      - Name: RemediationAccount
        Selector: $.Payload.account_id
        Type: String
      - Name: SecHubInputParams
        Selector: $.Payload.input_params
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: ''
        expected_control_id: 
          - 'SecretsManager.3'
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
  
  - name: GetInputParams
    action: 'aws:executeScript'
    outputs:
      - Name: unusedForDays
        Selector: $.Payload.unusedForDays
        Type: Integer
    inputs:
      InputPayload:
        SecHubInputParams: '{{ParseInput.SecHubInputParams}}'
        DefaultParams: { 
          "unusedForDays": 90
        }
        expected_control_id: [ 'SecretsManager.3' ]
      Runtime: python3.11
      Handler: get_input_params
      Script: |-
        %%SCRIPT=common/get_input_params.py%%

  - name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: ASR-RemoveUnusedSecret
      TargetLocations:
        - Accounts: [ '{{ParseInput.RemediationAccount}}' ]
          Regions: [ '{{ParseInput.RemediationRegion}}' ]
          ExecutionRoleName: '{{ RemediationRoleName }}'
      RuntimeParameters:
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'
        SecretARN: '{{ParseInput.SecretARN}}'
        UnusedForDays: '{{GetInputParams.unusedForDays}}'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Removed the unused secret.'
        UpdatedBy: 'ASR-AFSBP_1.0.0_SecretsManager.3'
      Workflow:
        Status: RESOLVED
    description: Update finding
