# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_EC2.23
 
  ## What does this document do?
  This document turns off AutoAcceptSharedAttachments on a transit gateway to ensure that only authorized VPC attachment requests are accepted.
 
  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * RemediationRoleName: (Optional) The name of the role that allows Automation to remediate the finding on your behalf.
 
  ## Output Parameters
  * Remediation.Output
 
  ## Documentation Links
  * [AWS FSBP v1.0.0 EC2.23](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-23)
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the EC2.23 finding
  RemediationRoleName:
    type: 'String'
    default: 'SO0111-DisableTGWAutoAcceptSharedAttachments'
    allowedPattern: '^[\w+=,.@-]+$'

outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
 
mainSteps:
  -
    name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding.Id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.finding.ProductArn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: TransitGatewayId
        Selector: $.Payload.resource_id
        Type: String
      - Name: RemediationRegion
        Selector: $.Payload.resource_region
        Type: String
      - Name: RemediationAccount
        Selector: $.Payload.account_id
        Type: String
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):ec2:[a-z]{2}-[a-z]+-\d{1}:\d{12}:transit-gateway\/(tgw-[a-z0-9\-]+)$'
        expected_control_id: 
          - 'EC2.23'
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
  -
    name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: ASR-DisableTGWAutoAcceptSharedAttachments
      TargetLocations:
        - Accounts: [ '{{ParseInput.RemediationAccount}}' ]
          Regions: [ '{{ParseInput.RemediationRegion}}' ]
          ExecutionRoleName: '{{ RemediationRoleName }}'
      RuntimeParameters:
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'
        TransitGatewayId: '{{ParseInput.TransitGatewayId}}'
  - 
    name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Disabled Transit Gateway from automatically accepting VPC attachment requests.'
        UpdatedBy: 'ASR-AFSBP_1.0.0_EC2.23'
      Workflow:
        Status: RESOLVED
    description: Update finding
