# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_IAM.7

  ## What does this document do?
  This document establishes a default password policy.

  ## Security Standards and Controls
  * AWS FSBP IAM.7

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AWS FSBP IAM.7](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-iam-7)

schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the IAM.7 finding
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'

mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: SecHubInputParams
        Selector: $.Payload.input_params
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: ''
        expected_control_id: [ 'IAM.7' ]
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
    isEnd: false
  - name: GetInputParams
    action: 'aws:executeScript'
    outputs:
      - Name: AllowUsersToChangePassword
        Selector: $.Payload.AllowUsersToChangePassword
        Type: Boolean
      - Name: HardExpiry
        Selector: $.Payload.HardExpiry
        Type: Boolean
      - Name: MaxPasswordAge
        Selector: $.Payload.MaxPasswordAge
        Type: Integer
      - Name: MinimumPasswordLength
        Selector: $.Payload.MinimumPasswordLength
        Type: Integer
      - Name: RequireSymbols
        Selector: $.Payload.RequireSymbols
        Type: Boolean
      - Name: RequireNumbers
        Selector: $.Payload.RequireNumbers
        Type: Boolean
      - Name: RequireUppercaseCharacters
        Selector: $.Payload.RequireUppercaseCharacters
        Type: Boolean
      - Name: RequireLowercaseCharacters
        Selector: $.Payload.RequireLowercaseCharacters
        Type: Boolean
      - Name: PasswordReusePrevention
        Selector: $.Payload.PasswordReusePrevention
        Type: Integer
    inputs:
      InputPayload:
        SecHubInputParams: '{{ParseInput.SecHubInputParams}}'
        DefaultParams: { 
        "AllowUsersToChangePassword": True, 
        "HardExpiry": True, 
        "MaxPasswordAge": 90, 
        "MinimumPasswordLength": 14, 
        "RequireSymbols": True, 
        "RequireNumbers": True, 
        "RequireUppercaseCharacters": True, 
        "RequireLowercaseCharacters": True, 
        "PasswordReusePrevention": 24 
        }
        expected_control_id: [ 'IAM.7' ]
      Runtime: python3.11
      Handler: get_input_params
      Script: |-
        %%SCRIPT=common/get_input_params.py%%
  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: ASR-SetIAMPasswordPolicy
      RuntimeParameters:
        AllowUsersToChangePassword: '{{GetInputParams.AllowUsersToChangePassword}}'
        HardExpiry: '{{GetInputParams.HardExpiry}}'
        MaxPasswordAge: '{{GetInputParams.MaxPasswordAge}}'
        MinimumPasswordLength: '{{GetInputParams.MinimumPasswordLength}}'
        RequireSymbols: '{{GetInputParams.RequireSymbols}}'
        RequireNumbers: '{{GetInputParams.RequireNumbers}}'
        RequireUppercaseCharacters: '{{GetInputParams.RequireUppercaseCharacters}}'
        RequireLowercaseCharacters: '{{GetInputParams.RequireLowercaseCharacters}}'
        PasswordReusePrevention: '{{GetInputParams.PasswordReusePrevention}}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-SetIAMPasswordPolicy'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Established a baseline password policy using the AWSConfigRemediation-SetIAMPasswordPolicy runbook.'
        UpdatedBy: 'ASR-AFSBP_1.0.0_IAM.7'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
