# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_CloudFront.12

  ## What does this document do?
  This document updates the origin domain on a given CloudFront distribution to prevent a malicious third party from creating the referenced bucket and serving their own content through your distribution.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AWS FSBP v1.0.0 CloudFront.12](https://docs.aws.amazon.com/securityhub/latest/userguide/cloudfront-controls.html#cloudfront-12)
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  AutomationAssumeRole:
    type: 'String'
    description: '(Required) The ARN of the role that allows Automation to perform the actions on your behalf.'
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  Finding:
    type: 'StringMap'
    description: 'The input from the Orchestrator Step function for the CloudFront.12 finding'
outputs:
- 'ParseInput.AffectedObject'
- 'Remediation.Output'
mainSteps:
- name: 'ParseInput'
  action: 'aws:executeScript'
  outputs:
    - Name: 'FindingId'
      Selector: '$.Payload.finding.Id'
      Type: 'String'
    - Name: 'ProductArn'
      Selector: '$.Payload.finding.ProductArn'
      Type: 'String'
    - Name: 'AffectedObject'
      Selector: '$.Payload.object'
      Type: 'StringMap'
    - Name: 'DistributionId'
      Selector: '$.Payload.resource_id'
      Type: 'String'
    - Name: 'RemediationRegion'
      Selector: '$.Payload.resource_region'
      Type: 'String'
    - Name: 'RemediationAccount'
      Selector: '$.Payload.account_id'
      Type: 'String'
  inputs:
    InputPayload:
      Finding: '{{Finding}}'
      parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):cloudfront::[0-9]{12}:distribution\/([A-Z0-9]*)$'
      expected_control_id:
      - 'CloudFront.12'
    Runtime: 'python3.8'
    Handler: 'parse_event'
    Script: |-
      %%SCRIPT=common/parse_input.py%%
- name: 'Remediation'
  action: 'aws:executeAutomation'
  isEnd: false
  inputs:
    DocumentName: ASR-SetCloudFrontOriginDomain
    RuntimeParameters:
      AutomationAssumeRole: 'arn:{{ global:AWS_PARTITION }}:iam::{{ global:ACCOUNT_ID }}:role/SO0111-SetCloudFrontOriginDomain'
      DistributionId: '{{ ParseInput.DistributionId }}'
- name: 'UpdateFinding'
  action: 'aws:executeAwsApi'
  inputs:
    Service: 'securityhub'
    Api: 'BatchUpdateFindings'
    FindingIdentifiers:
    - Id: '{{ ParseInput.FindingId }}'
      ProductArn: '{{ ParseInput.ProductArn }}'
    Note:
      Text: 'Configured origin domain for CloudFront distribution'
      UpdatedBy: 'ASR-AFSBP_1.0.0_CloudFront.12'
    Workflow:
      Status: 'RESOLVED'
  isEnd: true
