[tool.poetry]
name = "automated_security_response_on_aws"
package-mode = false

[tool.poetry.dependencies]
aws-lambda-powertools = {version = "3.1.0", extras = ["tracer"]}
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
